library(MASS)
library(rpart)
data("Pima.tr")
summary(Pima.tr)
set.seed(1111)
cart <- rpart(type~.,Pima.tr,control=rpart.control(cp=0))
summary(cart)
par(xpd=TRUE);plot(cart);text(cart)
cart_prune <- prune(cart,cp=0.03)
par(xpd = TRUE);plot(cart_prune); text(cart_prune)
